set IDENTITY_INSERT [dbo].[pais] on
go

insert into [pais] ([id_pais],[nombre]) values (1,'Afganistán')
insert into [pais] ([id_pais],[nombre]) values (2,'Albania')
insert into [pais] ([id_pais],[nombre]) values (3,'Alemania')
insert into [pais] ([id_pais],[nombre]) values (4,'Andorra')
insert into [pais] ([id_pais],[nombre]) values (5,'Angola')
insert into [pais] ([id_pais],[nombre]) values (6,'Antigua y Barbuda')
insert into [pais] ([id_pais],[nombre]) values (7,'Arabia Saudita')
insert into [pais] ([id_pais],[nombre]) values (8,'Argelia')
insert into [pais] ([id_pais],[nombre]) values (9,'Argentina')
insert into [pais] ([id_pais],[nombre]) values (10,'Armenia')
insert into [pais] ([id_pais],[nombre]) values (11,'Australia')
insert into [pais] ([id_pais],[nombre]) values (12,'Austria')
insert into [pais] ([id_pais],[nombre]) values (13,'Azerbaiyán')
insert into [pais] ([id_pais],[nombre]) values (14,'Bahamas')
insert into [pais] ([id_pais],[nombre]) values (15,'Bangladés')
insert into [pais] ([id_pais],[nombre]) values (16,'Barbados')
insert into [pais] ([id_pais],[nombre]) values (17,'Baréin')
insert into [pais] ([id_pais],[nombre]) values (18,'Bélgica')
insert into [pais] ([id_pais],[nombre]) values (19,'Belice')
insert into [pais] ([id_pais],[nombre]) values (20,'Benín')
insert into [pais] ([id_pais],[nombre]) values (21,'Bielorrusia')
insert into [pais] ([id_pais],[nombre]) values (22,'Birmania')
insert into [pais] ([id_pais],[nombre]) values (23,'Bolivia')
insert into [pais] ([id_pais],[nombre]) values (24,'Bosnia y Herzegovina')
insert into [pais] ([id_pais],[nombre]) values (25,'Botsuana')
insert into [pais] ([id_pais],[nombre]) values (26,'Brasil')
insert into [pais] ([id_pais],[nombre]) values (27,'Brunéi')
insert into [pais] ([id_pais],[nombre]) values (28,'Bulgaria')
insert into [pais] ([id_pais],[nombre]) values (29,'Burkina Faso')
insert into [pais] ([id_pais],[nombre]) values (30,'Burundi')
insert into [pais] ([id_pais],[nombre]) values (31,'Bután')
insert into [pais] ([id_pais],[nombre]) values (32,'Cabo Verde')
insert into [pais] ([id_pais],[nombre]) values (33,'Camboya')
insert into [pais] ([id_pais],[nombre]) values (34,'Camerún')
insert into [pais] ([id_pais],[nombre]) values (35,'Canadá')
insert into [pais] ([id_pais],[nombre]) values (36,'Catar')
insert into [pais] ([id_pais],[nombre]) values (37,'Chad')
insert into [pais] ([id_pais],[nombre]) values (38,'Chile')
insert into [pais] ([id_pais],[nombre]) values (39,'China')
insert into [pais] ([id_pais],[nombre]) values (40,'Chipre')
insert into [pais] ([id_pais],[nombre]) values (41,'Ciudad del Vaticano')
insert into [pais] ([id_pais],[nombre]) values (42,'Colombia')
insert into [pais] ([id_pais],[nombre]) values (43,'Comoras')
insert into [pais] ([id_pais],[nombre]) values (44,'Corea del Norte')
insert into [pais] ([id_pais],[nombre]) values (45,'Corea del Sur')
insert into [pais] ([id_pais],[nombre]) values (46,'Costa de Marfil')
insert into [pais] ([id_pais],[nombre]) values (47,'Costa Rica')
insert into [pais] ([id_pais],[nombre]) values (48,'Croacia')
insert into [pais] ([id_pais],[nombre]) values (49,'Cuba')
insert into [pais] ([id_pais],[nombre]) values (50,'Dinamarca')
insert into [pais] ([id_pais],[nombre]) values (51,'Dominica')
insert into [pais] ([id_pais],[nombre]) values (52,'Ecuador')
insert into [pais] ([id_pais],[nombre]) values (53,'Egipto')
insert into [pais] ([id_pais],[nombre]) values (54,'El Salvador')
insert into [pais] ([id_pais],[nombre]) values (55,'Emiratos Árabes Unidos')
insert into [pais] ([id_pais],[nombre]) values (56,'Eritrea')
insert into [pais] ([id_pais],[nombre]) values (57,'Eslovaquia')
insert into [pais] ([id_pais],[nombre]) values (58,'Eslovenia')
insert into [pais] ([id_pais],[nombre]) values (59,'España')
insert into [pais] ([id_pais],[nombre]) values (60,'Estados Unidos')
insert into [pais] ([id_pais],[nombre]) values (61,'Estonia')
insert into [pais] ([id_pais],[nombre]) values (62,'Etiopía')
insert into [pais] ([id_pais],[nombre]) values (63,'Filipinas')
insert into [pais] ([id_pais],[nombre]) values (64,'Finlandia')
insert into [pais] ([id_pais],[nombre]) values (65,'Fiyi')
insert into [pais] ([id_pais],[nombre]) values (66,'Francia')
insert into [pais] ([id_pais],[nombre]) values (67,'Gabón')
insert into [pais] ([id_pais],[nombre]) values (68,'Gambia')
insert into [pais] ([id_pais],[nombre]) values (69,'Georgia')
insert into [pais] ([id_pais],[nombre]) values (70,'Ghana')
insert into [pais] ([id_pais],[nombre]) values (71,'Granada')
insert into [pais] ([id_pais],[nombre]) values (72,'Grecia')
insert into [pais] ([id_pais],[nombre]) values (73,'Guatemala')
insert into [pais] ([id_pais],[nombre]) values (74,'Guyana')
insert into [pais] ([id_pais],[nombre]) values (75,'Guinea')
insert into [pais] ([id_pais],[nombre]) values (76,'Guinea ecuatorial')
insert into [pais] ([id_pais],[nombre]) values (77,'Guinea-Bisáu')
insert into [pais] ([id_pais],[nombre]) values (78,'Haití')
insert into [pais] ([id_pais],[nombre]) values (79,'Honduras')
insert into [pais] ([id_pais],[nombre]) values (80,'Hungría')
insert into [pais] ([id_pais],[nombre]) values (81,'India')
insert into [pais] ([id_pais],[nombre]) values (82,'Indonesia')
insert into [pais] ([id_pais],[nombre]) values (83,'Irak')
insert into [pais] ([id_pais],[nombre]) values (84,'Irán')
insert into [pais] ([id_pais],[nombre]) values (85,'Irlanda')
insert into [pais] ([id_pais],[nombre]) values (86,'Islandia')
insert into [pais] ([id_pais],[nombre]) values (87,'Islas Marshall')
insert into [pais] ([id_pais],[nombre]) values (88,'Islas Salomón')
insert into [pais] ([id_pais],[nombre]) values (89,'Israel')
insert into [pais] ([id_pais],[nombre]) values (90,'Italia')
insert into [pais] ([id_pais],[nombre]) values (91,'Jamaica')
insert into [pais] ([id_pais],[nombre]) values (92,'Japón')
insert into [pais] ([id_pais],[nombre]) values (93,'Jordania')
insert into [pais] ([id_pais],[nombre]) values (94,'Kazajistán')
insert into [pais] ([id_pais],[nombre]) values (95,'Kenia')
insert into [pais] ([id_pais],[nombre]) values (96,'Kirguistán')
insert into [pais] ([id_pais],[nombre]) values (97,'Kiribati')
insert into [pais] ([id_pais],[nombre]) values (98,'Kuwait')
insert into [pais] ([id_pais],[nombre]) values (99,'Laos')
insert into [pais] ([id_pais],[nombre]) values (100,'Lesoto')
insert into [pais] ([id_pais],[nombre]) values (101,'Letonia')
insert into [pais] ([id_pais],[nombre]) values (102,'Líbano')
insert into [pais] ([id_pais],[nombre]) values (103,'Liberia')
insert into [pais] ([id_pais],[nombre]) values (104,'Libia')
insert into [pais] ([id_pais],[nombre]) values (105,'Liechtenstein')
insert into [pais] ([id_pais],[nombre]) values (106,'Lituania')
insert into [pais] ([id_pais],[nombre]) values (107,'Luxemburgo')
insert into [pais] ([id_pais],[nombre]) values (108,'Madagascar')
insert into [pais] ([id_pais],[nombre]) values (109,'Malasia')
insert into [pais] ([id_pais],[nombre]) values (110,'Malaui')
insert into [pais] ([id_pais],[nombre]) values (111,'Maldivas')
insert into [pais] ([id_pais],[nombre]) values (112,'Malí')
insert into [pais] ([id_pais],[nombre]) values (113,'Malta')
insert into [pais] ([id_pais],[nombre]) values (114,'Marruecos')
insert into [pais] ([id_pais],[nombre]) values (115,'Mauricio')
insert into [pais] ([id_pais],[nombre]) values (116,'Mauritania')
insert into [pais] ([id_pais],[nombre]) values (117,'México')
insert into [pais] ([id_pais],[nombre]) values (118,'Micronesia')
insert into [pais] ([id_pais],[nombre]) values (119,'Moldavia')
insert into [pais] ([id_pais],[nombre]) values (120,'Mónaco')
insert into [pais] ([id_pais],[nombre]) values (121,'Mongolia')
insert into [pais] ([id_pais],[nombre]) values (122,'Montenegro')
insert into [pais] ([id_pais],[nombre]) values (123,'Mozambique')
insert into [pais] ([id_pais],[nombre]) values (124,'Namibia')
insert into [pais] ([id_pais],[nombre]) values (125,'Nauru')
insert into [pais] ([id_pais],[nombre]) values (126,'Nepal')
insert into [pais] ([id_pais],[nombre]) values (127,'Nicaragua')
insert into [pais] ([id_pais],[nombre]) values (128,'Níger')
insert into [pais] ([id_pais],[nombre]) values (129,'Nigeria')
insert into [pais] ([id_pais],[nombre]) values (130,'Noruega')
insert into [pais] ([id_pais],[nombre]) values (131,'Nueva Zelanda')
insert into [pais] ([id_pais],[nombre]) values (132,'Omán')
insert into [pais] ([id_pais],[nombre]) values (133,'Países Bajos')
insert into [pais] ([id_pais],[nombre]) values (134,'Pakistán')
insert into [pais] ([id_pais],[nombre]) values (135,'Palaos')
insert into [pais] ([id_pais],[nombre]) values (136,'Panamá')
insert into [pais] ([id_pais],[nombre]) values (137,'Papúa Nueva Guinea')
insert into [pais] ([id_pais],[nombre]) values (138,'Paraguay')
insert into [pais] ([id_pais],[nombre]) values (139,'Perú')
insert into [pais] ([id_pais],[nombre]) values (140,'Polonia')
insert into [pais] ([id_pais],[nombre]) values (141,'Portugal')
insert into [pais] ([id_pais],[nombre]) values (142,'Reino Unido')
insert into [pais] ([id_pais],[nombre]) values (143,'República Centroafricana')
insert into [pais] ([id_pais],[nombre]) values (144,'República Checa')
insert into [pais] ([id_pais],[nombre]) values (145,'República de Macedonia')
insert into [pais] ([id_pais],[nombre]) values (146,'República del Congo')
insert into [pais] ([id_pais],[nombre]) values (147,'República Democrática del Congo')
insert into [pais] ([id_pais],[nombre]) values (148,'República Dominicana')
insert into [pais] ([id_pais],[nombre]) values (149,'República Sudafricana')
insert into [pais] ([id_pais],[nombre]) values (150,'Ruanda')
insert into [pais] ([id_pais],[nombre]) values (151,'Rumanía')
insert into [pais] ([id_pais],[nombre]) values (152,'Rusia')
insert into [pais] ([id_pais],[nombre]) values (153,'Samoa')
insert into [pais] ([id_pais],[nombre]) values (154,'San Cristóbal y Nieves')
insert into [pais] ([id_pais],[nombre]) values (155,'San Marino')
insert into [pais] ([id_pais],[nombre]) values (156,'San Vicente y las Granadinas')
insert into [pais] ([id_pais],[nombre]) values (157,'Santa Lucía')
insert into [pais] ([id_pais],[nombre]) values (158,'Santo Tomé y Príncipe')
insert into [pais] ([id_pais],[nombre]) values (159,'Senegal')
insert into [pais] ([id_pais],[nombre]) values (160,'Serbia')
insert into [pais] ([id_pais],[nombre]) values (161,'Seychelles')
insert into [pais] ([id_pais],[nombre]) values (162,'Sierra Leona')
insert into [pais] ([id_pais],[nombre]) values (163,'Singapur')
insert into [pais] ([id_pais],[nombre]) values (164,'Siria')
insert into [pais] ([id_pais],[nombre]) values (165,'Somalia')
insert into [pais] ([id_pais],[nombre]) values (166,'Sri Lanka')
insert into [pais] ([id_pais],[nombre]) values (167,'Suazilandia')
insert into [pais] ([id_pais],[nombre]) values (168,'Sudán')
insert into [pais] ([id_pais],[nombre]) values (169,'Sudán del Sur')
insert into [pais] ([id_pais],[nombre]) values (170,'Suecia')
insert into [pais] ([id_pais],[nombre]) values (171,'Suiza')
insert into [pais] ([id_pais],[nombre]) values (172,'Surinam')
insert into [pais] ([id_pais],[nombre]) values (173,'Tailandia')
insert into [pais] ([id_pais],[nombre]) values (174,'Tanzania')
insert into [pais] ([id_pais],[nombre]) values (175,'Tayikistán')
insert into [pais] ([id_pais],[nombre]) values (176,'Timor Oriental')
insert into [pais] ([id_pais],[nombre]) values (177,'Togo')
insert into [pais] ([id_pais],[nombre]) values (178,'Tonga')
insert into [pais] ([id_pais],[nombre]) values (179,'Trinidad y Tobago')
insert into [pais] ([id_pais],[nombre]) values (180,'Túnez')
insert into [pais] ([id_pais],[nombre]) values (181,'Turkmenistán')
insert into [pais] ([id_pais],[nombre]) values (182,'Turquía')
insert into [pais] ([id_pais],[nombre]) values (183,'Tuvalu')
insert into [pais] ([id_pais],[nombre]) values (184,'Ucrania')
insert into [pais] ([id_pais],[nombre]) values (185,'Uganda')
insert into [pais] ([id_pais],[nombre]) values (186,'Uruguay')
insert into [pais] ([id_pais],[nombre]) values (187,'Uzbekistán')
insert into [pais] ([id_pais],[nombre]) values (188,'Vanuatu')
insert into [pais] ([id_pais],[nombre]) values (189,'Venezuela')
insert into [pais] ([id_pais],[nombre]) values (190,'Vietnam')
insert into [pais] ([id_pais],[nombre]) values (191,'Yemen')
insert into [pais] ([id_pais],[nombre]) values (192,'Yibuti')
insert into [pais] ([id_pais],[nombre]) values (193,'Zambia')
insert into [pais] ([id_pais],[nombre]) values (194,'Zimbabue')

set IDENTITY_INSERT [dbo].[pais] off
go